title: CrossWise
description: "Efficient Border Crossing system"
owner_name: Yash Parikh
github_username: illuminati1618
github_repo: "CrossWise"
baseurl: "/CrossWise"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
layouts_dir: _layouts
header_pages:
  - navigation/aboutus.md
  - navigation/search.md
  - navigation/machinelearning.md
  - navigation/directions.md
  - navigation/calendar.md

defaults:
  - scope:
      path: "" # Applies to all files
    values:
      layout: tailwind
